SET ANSI_PADDING ON
GO

IF INDEXPROPERTY(OBJECT_ID('dbo.SP_FURNITURES_LOG'), 'IDX_SP_FURNITURES_LOG_FURNITURE_ID', 'IndexID') IS NULL
	CREATE NONCLUSTERED INDEX [IDX_SP_FURNITURES_LOG_FURNITURE_ID] ON [dbo].[SP_FURNITURES_LOG]
	(
		[FURNITURE_ID] ASC
	) ON [PRIMARY]
GO


