SET ANSI_PADDING ON
GO

IF INDEXPROPERTY(OBJECT_ID('dbo.PR_APPLICATIONS'), 'IDX_PR_APPLICATIONS_INPUTDATETIME', 'IndexID') IS NULL
	CREATE NONCLUSTERED INDEX [IDX_PR_APPLICATIONS_INPUTDATETIME] ON [dbo].[PR_APPLICATIONS]
	(
		[INPUTDATETIME] ASC
	) ON [PRIMARY]
GO


