SET ANSI_PADDING ON
GO

IF INDEXPROPERTY(OBJECT_ID('dbo.SP_TYPEPROPERTIES_LOG'), 'IDX_SP_TYPEPROPERTIES_LOG_TYPE_ID', 'IndexID') IS NULL
	CREATE NONCLUSTERED INDEX [IDX_SP_TYPEPROPERTIES_LOG_TYPE_ID] ON [dbo].[SP_TYPEPROPERTIES_LOG]
	(
		[TYPE_ID] ASC
	) ON [PRIMARY]
GO


