SET ANSI_PADDING ON
GO

IF INDEXPROPERTY(OBJECT_ID('dbo.PR_APPLICATIONS_LOG'), 'IDX_PR_APPLICATIONS_LOG_APPLICATION_ID', 'IndexID') IS NULL
	CREATE NONCLUSTERED INDEX [IDX_PR_APPLICATIONS_LOG_APPLICATION_ID] ON [dbo].[PR_APPLICATIONS_LOG]
	(
		[APPLICATION_ID] ASC
	) ON [PRIMARY]
GO


