/*
DELETE FROM SP_PROPERTIES
DELETE FROM SP_TYPEPROPERTIES
*/

DECLARE
	@TYPE_NAME VARCHAR(255),
	@TYPE_SNAME VARCHAR(100);

SELECT
	@TYPE_NAME = 'Заявки.Статусы',
	@TYPE_SNAME = 'Заявки.Статусы'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_TYPEPROPERTIES WHERE TYPE_SNAME = @TYPE_SNAME)
	INSERT INTO SP_TYPEPROPERTIES (TYPE_NAME, TYPE_SNAME)
	VALUES
	(@TYPE_NAME, @TYPE_SNAME)

SELECT
	@TYPE_NAME = 'Заявки.Причины',
	@TYPE_SNAME = 'Заявки.Причины'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_TYPEPROPERTIES WHERE TYPE_SNAME = @TYPE_SNAME)
	INSERT INTO SP_TYPEPROPERTIES (TYPE_NAME, TYPE_SNAME)
	VALUES
	(@TYPE_NAME, @TYPE_SNAME)

SELECT
	@TYPE_NAME = 'Заявки.СтатусыРешений',
	@TYPE_SNAME = 'Заявки.СтатусыРешений'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_TYPEPROPERTIES WHERE TYPE_SNAME = @TYPE_SNAME)
	INSERT INTO SP_TYPEPROPERTIES (TYPE_NAME, TYPE_SNAME)
	VALUES
	(@TYPE_NAME, @TYPE_SNAME)

SELECT
	@TYPE_NAME = 'Заявки.ТипыРешений',
	@TYPE_SNAME = 'Заявки.ТипыРешений'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_TYPEPROPERTIES WHERE TYPE_SNAME = @TYPE_SNAME)
	INSERT INTO SP_TYPEPROPERTIES (TYPE_NAME, TYPE_SNAME)
	VALUES
	(@TYPE_NAME, @TYPE_SNAME)