/*
DELETE FROM SP_PROPERTIES
*/

DECLARE
	@PROPERTY_NAME VARCHAR(255),
	@PROPERTY_SNAME VARCHAR(100),
	@TYPE_ID INT,
	@TYPE_SNAME VARCHAR(100);

SET	@TYPE_SNAME = 'Заявки.Статусы'
SET @TYPE_ID = dbo.[udf_GET_TYPEPROPERTY](@TYPE_SNAME)

SELECT
	@PROPERTY_NAME = 'подана',
	@PROPERTY_SNAME = 'подана'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SELECT
	@PROPERTY_NAME = 'в работе',
	@PROPERTY_SNAME = 'в работе'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SELECT
	@PROPERTY_NAME = 'завершена',
	@PROPERTY_SNAME = 'завершена'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SET	@TYPE_SNAME = 'Заявки.Причины'
SET @TYPE_ID = dbo.[udf_GET_TYPEPROPERTY](@TYPE_SNAME)

SELECT
	@PROPERTY_NAME = 'поломка',
	@PROPERTY_SNAME = 'поломка'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SET	@TYPE_SNAME = 'Заявки.СтатусыРешений'
SET @TYPE_ID = dbo.[udf_GET_TYPEPROPERTY](@TYPE_SNAME)

SELECT
	@PROPERTY_NAME = 'одобрено',
	@PROPERTY_SNAME = 'одобрено'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SELECT
	@PROPERTY_NAME = 'отклонено',
	@PROPERTY_SNAME = 'отклонено'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SELECT
	@PROPERTY_NAME = 'на рассмотрении',
	@PROPERTY_SNAME = 'на рассмотрении'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SET	@TYPE_SNAME = 'Заявки.ТипыРешений'
SET @TYPE_ID = dbo.[udf_GET_TYPEPROPERTY](@TYPE_SNAME)

SELECT
	@PROPERTY_NAME = 'замена',
	@PROPERTY_SNAME = 'замена'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)

SELECT
	@PROPERTY_NAME = 'ремонт',
	@PROPERTY_SNAME = 'ремонт'

IF NOT EXISTS(SELECT TOP 1 NULL FROM SP_PROPERTIES WHERE TYPE_ID = @TYPE_ID AND PROPERTY_SNAME = @PROPERTY_SNAME)
	INSERT INTO SP_PROPERTIES (TYPE_ID, PROPERTY_NAME, PROPERTY_SNAME)
	VALUES
	(@TYPE_ID, @PROPERTY_NAME, @PROPERTY_SNAME)