SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.SP_FURNITURES_LOG') IS NULL
	CREATE TABLE [dbo].[SP_FURNITURES_LOG](
		[FURNITURE_ID] [INT] NULL,
		[FURNITURE_NAME] [VARCHAR](255) NULL,
		[LOG_TYPE] VARCHAR(6) NULL,
		[INPUTDATETIME] DATETIME NULL CONSTRAINT [DF_SP_FURNITURES_LOG_INPUTDATETIME] DEFAULT (GETDATE()),
		[INPUTUSER] VARCHAR(255) NULL CONSTRAINT [DF_SP_FURNITURES_LOG_INPUTUSER] DEFAULT (SUSER_SNAME())
	) ON [PRIMARY]
GO