SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.SP_PERSONS') IS NULL
	CREATE TABLE [dbo].[SP_PERSONS](
		[PERSON_GUID] [VARCHAR](36) NOT NULL,
		[PERSON_NAME1] [VARCHAR](255) NOT NULL,
		[PERSON_NAME2] [VARCHAR](255) NOT NULL,
		[PERSON_NAME3] [VARCHAR](255) NULL,
		CONSTRAINT [PK_SP_PERSONS] PRIMARY KEY CLUSTERED 
		(
			[PERSON_GUID] ASC
		) ON [PRIMARY]
	) ON [PRIMARY]
GO

