SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.SP_PROPERTIES') IS NULL
	CREATE TABLE [dbo].[SP_PROPERTIES](
		[PROPERTY_ID] [SMALLINT] IDENTITY(1,1) NOT NULL,
		[TYPE_ID] [SMALLINT] NOT NULL,
		[PROPERTY_NAME] [VARCHAR](255) NOT NULL,
		[PROPERTY_SNAME] [VARCHAR](100) NOT NULL,
		 CONSTRAINT [PK_SP_PROPERTIES] PRIMARY KEY CLUSTERED 
		(
			[PROPERTY_ID] ASC
		) ON [PRIMARY]
	) ON [PRIMARY]
GO

IF OBJECT_ID('dbo.FK_SP_PROPERTIES_SP_TYPEPROPERTIES') IS NULL
BEGIN
	ALTER TABLE [dbo].[SP_PROPERTIES]  WITH CHECK ADD  CONSTRAINT [FK_SP_PROPERTIES_SP_TYPEPROPERTIES] FOREIGN KEY([TYPE_ID])
	REFERENCES [dbo].[SP_TYPEPROPERTIES] ([TYPE_ID])

	ALTER TABLE [dbo].[SP_PROPERTIES] CHECK CONSTRAINT [FK_SP_PROPERTIES_SP_TYPEPROPERTIES]
END
GO


