SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.SP_PERSONS_LOG') IS NULL
	CREATE TABLE [dbo].[SP_PERSONS_LOG](
		[PERSON_GUID] [VARCHAR](36) NULL,
		[PERSON_NAME1] [VARCHAR](255) NULL,
		[PERSON_NAME2] [VARCHAR](255) NULL,
		[PERSON_NAME3] [VARCHAR](255) NULL,
		[LOG_TYPE] VARCHAR(6) NULL,
		[INPUTDATETIME] DATETIME NULL CONSTRAINT [DF_SP_PERSONS_LOG_INPUTDATETIME] DEFAULT (GETDATE()),
		[INPUTUSER] VARCHAR(255) NULL CONSTRAINT [DF_SP_PERSONS_LOG_INPUTUSER] DEFAULT (SUSER_SNAME())
	) ON [PRIMARY]
GO

