SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.SP_TYPEPROPERTIES') IS NULL
	CREATE TABLE [dbo].[SP_TYPEPROPERTIES](
		[TYPE_ID] [SMALLINT] IDENTITY(1,1) NOT NULL,
		[TYPE_NAME] [VARCHAR](255) NOT NULL,
		[TYPE_SNAME] [VARCHAR](100) NOT NULL,
		CONSTRAINT [PK_SP_TYPES] PRIMARY KEY CLUSTERED 
		(
			[TYPE_ID] ASC
		) ON [PRIMARY]
	) ON [PRIMARY]
GO


