SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.triud_PR_APPLICATIONS') IS NOT NULL
	DROP TRIGGER triud_PR_APPLICATIONS
GO

CREATE TRIGGER triud_PR_APPLICATIONS 
   ON dbo.PR_APPLICATIONS 
   AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
	DECLARE @LOG_TYPE VARCHAR(6);
	
	IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
		AND
		NOT EXISTS(SELECT TOP 1 NULL FROM DELETED)
		SET @LOG_TYPE = 'INSERT'
	ELSE
		IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
			AND
			EXISTS(SELECT TOP 1 NULL FROM DELETED)
			SET @LOG_TYPE = 'UPDATE'
		ELSE
			SET @LOG_TYPE = 'DELETE'


	INSERT INTO PR_APPLICATIONS_LOG
		([APPLICATION_ID]
		,[FURNITURE_ID]
		,[APPLICANT_GUID]
		,[REASON_ID]
		,[MANAGER_GUID]
		,[RESULUTION_ID]
		,[resolutionPeriod]
		,[SOLUTION_ID]
		,[STATUS_ID]
		,[LOG_TYPE])
	SELECT 
		[APPLICATION_ID]
		,[FURNITURE_ID]
		,[APPLICANT_GUID]
		,[REASON_ID]
		,[MANAGER_GUID]
		,[RESULUTION_ID]
		,[resolutionPeriod]
		,[SOLUTION_ID]
		,[STATUS_ID]
		,@LOG_TYPE
	FROM INSERTED

	IF @@ROWCOUNT = 0
		INSERT INTO PR_APPLICATIONS_LOG
			([APPLICATION_ID]
			,[FURNITURE_ID]
			,[APPLICANT_GUID]
			,[REASON_ID]
			,[MANAGER_GUID]
			,[RESULUTION_ID]
			,[resolutionPeriod]
			,[SOLUTION_ID]
			,[STATUS_ID]
			,[LOG_TYPE])
		SELECT 
			[APPLICATION_ID]
			,[FURNITURE_ID]
			,[APPLICANT_GUID]
			,[REASON_ID]
			,[MANAGER_GUID]
			,[RESULUTION_ID]
			,[resolutionPeriod]
			,[SOLUTION_ID]
			,[STATUS_ID]
			,@LOG_TYPE
		FROM DELETED
END
GO
