SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.triud_SP_TYPEPROPERTIES') IS NOT NULL
	DROP TRIGGER dbo.triud_SP_TYPEPROPERTIES
GO

CREATE TRIGGER dbo.triud_SP_TYPEPROPERTIES
   ON dbo.SP_TYPEPROPERTIES
   AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
	DECLARE @LOG_TYPE VARCHAR(6);
	
	IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
		AND
		NOT EXISTS(SELECT TOP 1 NULL FROM DELETED)
		SET @LOG_TYPE = 'INSERT'
	ELSE
		IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
			AND
			EXISTS(SELECT TOP 1 NULL FROM DELETED)
			SET @LOG_TYPE = 'UPDATE'
		ELSE
			SET @LOG_TYPE = 'DELETE'

	INSERT INTO [SP_TYPEPROPERTIES_LOG]
		([TYPE_ID]
		 ,[TYPE_NAME]
		 ,[TYPE_SNAME]
		 ,[LOG_TYPE])
	SELECT
		 [TYPE_ID]
		 ,[TYPE_NAME]
		 ,[TYPE_SNAME]
		 ,@LOG_TYPE
	FROM INSERTED

	IF @@ROWCOUNT = 0
		INSERT INTO [SP_TYPEPROPERTIES_LOG]
			([TYPE_ID]
			 ,[TYPE_NAME]
			 ,[TYPE_SNAME]
			 ,[LOG_TYPE])
		SELECT
			 [TYPE_ID]
			 ,[TYPE_NAME]
			 ,[TYPE_SNAME]
			 ,@LOG_TYPE
		FROM DELETED
END
GO
