SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.triud_SP_FURNITURES') IS NOT NULL
	DROP TRIGGER triud_SP_FURNITURES
GO

CREATE TRIGGER triud_SP_FURNITURES
   ON dbo.SP_FURNITURES
   AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
	DECLARE @LOG_TYPE VARCHAR(6);
	
	IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
		AND
		NOT EXISTS(SELECT TOP 1 NULL FROM DELETED)
		SET @LOG_TYPE = 'INSERT'
	ELSE
		IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
			AND
			EXISTS(SELECT TOP 1 NULL FROM DELETED)
			SET @LOG_TYPE = 'UPDATE'
		ELSE
			SET @LOG_TYPE = 'DELETE'

	INSERT INTO [SP_FURNITURES_LOG]
		([FURNITURE_ID]
		,[FURNITURE_NAME]
		,[LOG_TYPE])
	SELECT
		[FURNITURE_ID]
		,[FURNITURE_NAME]
		,@LOG_TYPE
	FROM INSERTED

	IF @@ROWCOUNT = 0
		INSERT INTO [SP_FURNITURES_LOG]
			([FURNITURE_ID]
			,[FURNITURE_NAME]
			,[LOG_TYPE])
		SELECT
			[FURNITURE_ID]
			,[FURNITURE_NAME]
			,@LOG_TYPE
		FROM DELETED
END
GO
