SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.triud_SP_PROPERTIES') IS NOT NULL
	DROP TRIGGER dbo.triud_SP_PROPERTIES
GO

CREATE TRIGGER dbo.triud_SP_PROPERTIES
   ON dbo.SP_PROPERTIES
   AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
	DECLARE @LOG_TYPE VARCHAR(6);
	
	IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
		AND
		NOT EXISTS(SELECT TOP 1 NULL FROM DELETED)
		SET @LOG_TYPE = 'INSERT'
	ELSE
		IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
			AND
			EXISTS(SELECT TOP 1 NULL FROM DELETED)
			SET @LOG_TYPE = 'UPDATE'
		ELSE
			SET @LOG_TYPE = 'DELETE'

	INSERT INTO [SP_PROPERTIES_LOG]
		([PROPERTY_ID]
		 ,[TYPE_ID]
		 ,[PROPERTY_NAME]
		 ,[PROPERTY_SNAME]
		 ,[LOG_TYPE])
	SELECT
		[PROPERTY_ID]
		 ,[TYPE_ID]
		 ,[PROPERTY_NAME]
		 ,[PROPERTY_SNAME]
		 ,@LOG_TYPE
	FROM INSERTED

	IF @@ROWCOUNT = 0
		INSERT INTO [SP_PROPERTIES_LOG]
			([PROPERTY_ID]
			 ,[TYPE_ID]
			 ,[PROPERTY_NAME]
			 ,[PROPERTY_SNAME]
			 ,[LOG_TYPE])
		SELECT
			[PROPERTY_ID]
			 ,[TYPE_ID]
			 ,[PROPERTY_NAME]
			 ,[PROPERTY_SNAME]
			 ,@LOG_TYPE
		FROM DELETED
END
GO
