SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.triud_SP_PERSONS') IS NOT NULL
	DROP TRIGGER dbo.triud_SP_PERSONS
GO

CREATE TRIGGER dbo.triud_SP_PERSONS
   ON dbo.SP_PERSONS
   AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
	DECLARE @LOG_TYPE VARCHAR(6);
	
	IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
		AND
		NOT EXISTS(SELECT TOP 1 NULL FROM DELETED)
		SET @LOG_TYPE = 'INSERT'
	ELSE
		IF EXISTS(SELECT TOP 1 NULL FROM INSERTED)
			AND
			EXISTS(SELECT TOP 1 NULL FROM DELETED)
			SET @LOG_TYPE = 'UPDATE'
		ELSE
			SET @LOG_TYPE = 'DELETE'

	INSERT INTO [SP_PERSONS_LOG]
		([PERSON_GUID]
		 ,[PERSON_NAME1]
		 ,[PERSON_NAME2]
		 ,[PERSON_NAME3]
		 ,[LOG_TYPE])
	SELECT
		[PERSON_GUID]
		 ,[PERSON_NAME1]
		 ,[PERSON_NAME2]
		 ,[PERSON_NAME3]
		 ,@LOG_TYPE
	FROM INSERTED

	IF @@ROWCOUNT = 0
		INSERT INTO [SP_PERSONS_LOG]
			([PERSON_GUID]
			 ,[PERSON_NAME1]
			 ,[PERSON_NAME2]
			 ,[PERSON_NAME3]
			 ,[LOG_TYPE])
		SELECT
			[PERSON_GUID]
			 ,[PERSON_NAME1]
			 ,[PERSON_NAME2]
			 ,[PERSON_NAME3]
			 ,@LOG_TYPE
		FROM DELETED
END
GO
