SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_SP_PERSONS_DELETE') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SP_PERSONS_DELETE]
GO

/*
[{"PERSON_GUID":"GUID_Александров","PERSON_NAME1":"Александров","PERSON_NAME2":"Владимир","PERSON_NAME3":""}]
*/

CREATE PROCEDURE [dbo].[usp_SP_PERSONS_DELETE] 
	@JSON NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRY
		DECLARE @PERSON_GUID VARCHAR(36);
		
		SELECT
			@PERSON_GUID = PERSON_GUID
		FROM OPENJSON(@JSON) WITH (
			PERSON_GUID VARCHAR(36)
		)

		DELETE SP_PERSONS WHERE PERSON_GUID = @PERSON_GUID
		
		RETURN 0;
	END TRY
	BEGIN CATCH
		DECLARE @ErrMessage VARCHAR(MAX) = 'Ошибка удаления (SP_PERSONS):' + CHAR(13) + char(10);
		SET @ErrMessage = @ErrMessage + '(' + CAST(ERROR_NUMBER() AS VARCHAR(MAX)) + ') ' +  ERROR_MESSAGE();
		RAISERROR(@ErrMessage, 16, 1);
		RETURN 1;
	END CATCH
END
GO
