SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_SP_PERSONS_INSERT') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SP_PERSONS_INSERT]
GO

CREATE PROCEDURE [dbo].[usp_SP_PERSONS_INSERT] 
	@JSON NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRY

		INSERT INTO SP_PERSONS
			(PERSON_GUID
			, PERSON_NAME1
			, PERSON_NAME2
			, PERSON_NAME3)
		SELECT 
			j.PERSON_GUID
			, j.PERSON_NAME1
			, j.PERSON_NAME2
			, j.PERSON_NAME3
		FROM OPENJSON(@JSON) WITH (
			PERSON_GUID VARCHAR(36)
			, PERSON_NAME1 VARCHAR(255)
			, PERSON_NAME2 VARCHAR(255)
			, PERSON_NAME3 VARCHAR(255)
		) j
		
		RETURN 0;
	END TRY
	BEGIN CATCH
		DECLARE @ErrMessage VARCHAR(MAX) = 'Ошибка при создании (SP_PERSONS):' + CHAR(13) + CHAR(10);
		SET @ErrMessage = @ErrMessage + '(' + CAST(ERROR_NUMBER() AS VARCHAR(MAX)) + ') ' +  ERROR_MESSAGE();
		RAISERROR(@ErrMessage, 16, 1);
		RETURN 1;
	END CATCH
END
GO
