SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_SP_FURNITURES_UPDATE') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SP_FURNITURES_UPDATE]
GO

CREATE PROCEDURE [dbo].[usp_SP_FURNITURES_UPDATE] 
	@JSON NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRY

		UPDATE f
		SET
			f.FURNITURE_NAME = j.FURNITURE_NAME
		FROM OPENJSON(@JSON) WITH (
			FURNITURE_ID INT
			, FURNITURE_NAME VARCHAR(255)
		) j
		JOIN SP_FURNITURES f ON j.FURNITURE_ID = f.FURNITURE_ID
		
		RETURN 0;
	END TRY
	BEGIN CATCH
		DECLARE @ErrMessage VARCHAR(MAX) = 'Ошибка при обновлении (SP_FURNITURES):' + CHAR(13) + CHAR(10);
		SET @ErrMessage = @ErrMessage + '(' + CAST(ERROR_NUMBER() AS VARCHAR(MAX)) + ') ' +  ERROR_MESSAGE();
		RAISERROR(@ErrMessage, 16, 1);
		RETURN 1;
	END CATCH
END
GO
