SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_SP_PROPERTIES_UPDATE') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SP_PROPERTIES_UPDATE]
GO

CREATE PROCEDURE [dbo].[usp_SP_PROPERTIES_UPDATE] 
	@JSON NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRY

		UPDATE p
		SET
			p.TYPE_ID = j.TYPE_ID
			, p.PROPERTY_NAME = j.PROPERTY_NAME
			, p.PROPERTY_SNAME = j.PROPERTY_SNAME
		FROM OPENJSON(@JSON) WITH (
			PROPERTY_ID SMALLINT
			, TYPE_ID SMALLINT
			, PROPERTY_NAME VARCHAR(255)
			, PROPERTY_SNAME VARCHAR(100)
		) j
		JOIN SP_PROPERTIES p ON p.PROPERTY_ID = j.PROPERTY_ID
		
		RETURN 0;
	END TRY
	BEGIN CATCH
		DECLARE @ErrMessage VARCHAR(MAX) = 'Ошибка при обновлении (SP_PROPERTIES):' + CHAR(13) + CHAR(10);
		SET @ErrMessage = @ErrMessage + '(' + CAST(ERROR_NUMBER() AS VARCHAR(MAX)) + ') ' +  ERROR_MESSAGE();
		RAISERROR(@ErrMessage, 16, 1);
		RETURN 1;
	END CATCH
END
GO
