SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_SP_TYPEPROPERTIES_DELETE') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SP_TYPEPROPERTIES_DELETE]
GO

CREATE PROCEDURE [dbo].[usp_SP_TYPEPROPERTIES_DELETE] 
	@JSON NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRY
		DECLARE @TYPE_ID SMALLINT;
		
		SELECT
			@TYPE_ID = TYPE_ID
		FROM OPENJSON(@JSON) WITH (
			TYPE_ID SMALLINT
		)

		DELETE SP_TYPEPROPERTIES WHERE TYPE_ID = @TYPE_ID
		
		RETURN 0;
	END TRY
	BEGIN CATCH
		DECLARE @ErrMessage VARCHAR(MAX) = 'Ошибка удаления (SP_TYPEPROPERTIES):' + CHAR(13) + CHAR(10);
		SET @ErrMessage = @ErrMessage + '(' + CAST(ERROR_NUMBER() AS VARCHAR(MAX)) + ') ' +  ERROR_MESSAGE();
		RAISERROR(@ErrMessage, 16, 1);
		RETURN 1;
	END CATCH
END
GO
