SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_SP_TYPEPROPERTIES_INSERT') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SP_TYPEPROPERTIES_INSERT]
GO

CREATE PROCEDURE [dbo].[usp_SP_TYPEPROPERTIES_INSERT] 
	@JSON NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRY
		DECLARE
			@TYPE_NAME VARCHAR(255),
			@TYPE_SNAME VARCHAR(100)

		SELECT 
			@TYPE_NAME = j.[TYPE_NAME]
			, @TYPE_SNAME = j.[TYPE_SNAME]
		FROM OPENJSON(@JSON) WITH (
			[TYPE_NAME] VARCHAR(255)
			, [TYPE_SNAME] VARCHAR(100)
		) j

		INSERT INTO SP_TYPEPROPERTIES
			([TYPE_NAME]
			, [TYPE_SNAME])
		VALUES
			(@TYPE_NAME
			, @TYPE_SNAME)
		
		RETURN 0;
	END TRY
	BEGIN CATCH
		DECLARE @ErrMessage VARCHAR(MAX) = 'Ошибка при создании (SP_TYPEPROPERTIES):' + CHAR(13) + CHAR(10);
		SET @ErrMessage = @ErrMessage + '(' + CAST(ERROR_NUMBER() AS VARCHAR(MAX)) + ') ' +  ERROR_MESSAGE();
		RAISERROR(@ErrMessage, 16, 1);
		RETURN 1;
	END CATCH
END
GO
