SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_SP_PROPERTIES_INSERT') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SP_PROPERTIES_INSERT]
GO

CREATE PROCEDURE [dbo].[usp_SP_PROPERTIES_INSERT] 
	@JSON NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRY

		INSERT INTO SP_PROPERTIES
			([TYPE_ID]
			, [PROPERTY_NAME]
			, [PROPERTY_SNAME])
		SELECT 
			j.[TYPE_ID]
			, j.[PROPERTY_NAME]
			, j.[PROPERTY_SNAME]
		FROM OPENJSON(@JSON) WITH (
			[TYPE_ID] SMALLINT
			, [PROPERTY_NAME] VARCHAR(255)
			, [PROPERTY_SNAME] VARCHAR(100)
		) j
		
		RETURN 0;
	END TRY
	BEGIN CATCH
		DECLARE @ErrMessage VARCHAR(MAX) = 'Ошибка при создании (SP_PROPERTIES):' + CHAR(13) + CHAR(10);
		SET @ErrMessage = @ErrMessage + '(' + CAST(ERROR_NUMBER() AS VARCHAR(MAX)) + ') ' +  ERROR_MESSAGE();
		RAISERROR(@ErrMessage, 16, 1);
		RETURN 1;
	END CATCH
END
GO
