SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.usp_PR_APPLICATIONS_SELECT') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_PR_APPLICATIONS_SELECT]
GO

CREATE PROCEDURE [dbo].[usp_PR_APPLICATIONS_SELECT] 
	@DATEFROM DATE = NULL
	, @DATETO DATE = NULL
AS
BEGIN
	SET @DATEFROM = ISNULL(@DATEFROM, CAST(GETDATE() AS DATE));
	SET @DATETO = ISNULL(@DATETO, CAST(GETDATE() AS DATE));

	SELECT
		*
	FROM VW_PR_APPLICATION
	WHERE
		CAST(INPUTDATETIME AS DATE) BETWEEN @DATEFROM AND @DATETO
END
GO