IF OBJECT_ID('dbo.VW_PR_APPLICATION') IS NOT NULL
	DROP VIEW [dbo].[VW_PR_APPLICATION]
GO

CREATE VIEW [dbo].[VW_PR_APPLICATION]
AS

SELECT
      a.[FURNITURE_ID]
      ,p1.PERSON_NAME1 + ISNULL(' ' +  NULLIF(p1.PERSON_NAME2, ''), '') + ISNULL(' ' + NULLIF(p1.PERSON_NAME3, ''), '') as [APPLICANT]
      ,pr1.PROPERTY_NAME [REASON]
      ,p2.PERSON_NAME1 + ISNULL(' ' +  NULLIF(p2.PERSON_NAME2, ''), '') + ISNULL(' ' + NULLIF(p2.PERSON_NAME3, ''), '') as [MANAGER]
      ,pr2.PROPERTY_NAME [RESULUTION]
      ,a.[resolutionPeriod]
      ,pr3.PROPERTY_NAME [SOLUTION]
      ,pr4.PROPERTY_NAME [STATUS]
      ,a.[INPUTDATETIME]
FROM PR_APPLICATIONS a WITH(NOLOCK)
LEFT JOIN SP_PERSONS p1 WITH(NOLOCK) ON a.[APPLICANT_GUID] = p1.PERSON_GUID
LEFT JOIN SP_PERSONS p2 WITH(NOLOCK) ON a.[MANAGER_GUID] = p2.PERSON_GUID
LEFT JOIN SP_PROPERTIES pr1 WITH(NOLOCK) ON pr1.PROPERTY_ID = a.[REASON_ID]
LEFT JOIN SP_PROPERTIES pr2 WITH(NOLOCK) ON pr2.PROPERTY_ID = a.[RESULUTION_ID]
LEFT JOIN SP_PROPERTIES pr3 WITH(NOLOCK) ON pr3.PROPERTY_ID = a.[SOLUTION_ID]
LEFT JOIN SP_PROPERTIES pr4 WITH(NOLOCK) ON pr4.PROPERTY_ID = a.[STATUS_ID]